### ISSUE TITLE
Error when executing: "The size of tensor a (104) must match the size of tensor b (102) at non-singleton dimension 2"

### ISSUE THREAD

**Issue by aegis72** [jamesWalker55/comfyui-p2ldgan#1]
Hi there! I received this when trying this out. I loaded an image my daughter painted:

![image](https://github.com/jamesWalker55/comfyui-p2ldgan/assets/118572301/3ac391d0-3be6-4519-888c-e569b1d650d4)

In the command window, this precedes the error: Resizing image from (1611, 1289) to (1024, 819). I thought maybe this was the broken step, so I resized the image to 1024x819 manually, then reran but got the same error (Resizing image from (1024, 819) to (1024, 819) )

**Any idea what I'm doing wrong?** The model is in the custom_nodes/comfyui-p2ldgan/checkpoints directory using the default filename. I am using ComfyUI portable, which otherwise functions normally.

Text of the error is:
```
Error occurred when executing P2LDGAN:

The size of tensor a (104) must match the size of tensor b (102) at non-singleton dimension 2

File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-p2ldgan\nodes.py", line 74, in execute
ld_images = self.generate_line_drawing(
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-p2ldgan\nodes.py", line 96, in generate_line_drawing
ld_images = generator(images)
File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-p2ldgan\models\models.py", line 74, in forward
u1 = self.up1(
File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-p2ldgan\models\blocks.py", line 67, in forward
x = torch.add(x, skip_input4)
```

**Comment by jamesWalker55** [comment]
It seems that P2LDGAN can't handle image dimensions that aren't divisible by 16, in your case the image height of 819 isn't divisible by 16, causing an error in the model. I've just updated the node to show a message if the image isn't the right size with https://github.com/jamesWalker55/comfyui-p2ldgan/commit/cfa09c88008df20a5cf47e81ca0de70b8c1f1d6c.

You can try resizing the image to 1024x816 for example, let me know if that stops the error.

**Comment by aegis72** [comment]
Thanks; unfortunately it did not but the above info is good to know. I recropped to 512x512 though, and that worked. Will it function on non-square images?

![image](https://github.com/jamesWalker55/comfyui-p2ldgan/assets/118572301/ac751491-e1e0-476b-98f4-deda00809e07)

**Comment by jamesWalker55** [comment]
It should handle on non-square images - I've just tried it with an image that's resized to 1024x816 and it works:

![image](https://github.com/jamesWalker55/comfyui-p2ldgan/assets/30405220/ae1c785a-1770-4013-b76d-4aca78fba42e)

You might need a separate node to resize the image to the right size before putting it in P2LDGAN.

Also, from your screenshot it looks like you haven't updated the P2LDGAN node yet, it's a good idea to update the node since the node now tells you the image size it received when the error happens.

**Comment by aegis72** [comment]
OK, will do. I installed it using the Comfy Manager just today but I will try to update. I did a resize-by-node thing the other day so I will also integrate that into the workflow. Thank you so much for making this and for the speedy replies!!!!

**Comment by aegis72** [comment]
I also noticed that the error occurs if you fail, as I did, to change the resolution from 512 to 1024  when using an image w/ a 1024 side. I changed that and it worked. Thanks again!

**Comment by aegis72** [comment]
Thanks again! Here's a finished workflow using it. I added nodes from MBT, WAS, and ComfyMath:
![image](https://github.com/jamesWalker55/comfyui-p2ldgan/assets/118572301/b720f11a-552a-4667-90b0-a76c4d6b9592)

Works like a charm!
